version: '3.4'

services:
  main:
    build: .
    command: npm run start:dev
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./src:/var/www/src

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
